### ISSUE TITLE
PatchCollection - TypeError: array([ 1.]) is not JSON serializable

### ISSUE THREAD

**Issue by omn14** [mpld3/mpld3#434]
I want to make a .html with a plot of some patches in a patch collection.
Im running the example from "https://matplotlib.org/examples/api/patch_collection.html"

Could someone please help?

thanks,

i get this error:

> Traceback (most recent call last):
  File "ttt.py", line 55, in <module>
    htmlfil.write(mpld3.fig_to_html(fig))
  File "/usr/local/lib/python2.7/dist-packages/mpld3/_display.py", line 251, in fig_to_html
    figure_json=json.dumps(figure_json, cls=NumpyEncoder),
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/_display.py", line 138, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array([ 1.]) is not JSON serializable

**Comment by shouldsee** [comment]
I was having a similar error. It seems `matplotlib.collections.pathcollection` did not sanitise its dictionary enough and mpld3 relies on a "NumpyEncoder" serialise the dictionary. 

Fix:
In `_display.py`
```python
class NumpyEncoder(json.JSONEncoder):
    """ Special json encoder for numpy types """
    def default(self, obj):
        if isinstance(obj, (numpy.int_, numpy.intc, numpy.intp, numpy.int8,
            numpy.int16, numpy.int32, numpy.int64, numpy.uint8,
            numpy.uint16,numpy.uint32, numpy.uint64)):
            return int(obj)
        elif isinstance(obj, (numpy.float_, numpy.float16, numpy.float32, 
            numpy.float64)):
            return float(obj)
        elif isinstance(obj,(numpy.ndarray,)): #### This is the fix
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)
```

**Comment by hchaithanya** [comment]
I am facing similar error or my python code: analyse.py:
```
def svm_analyze_AHE(file_name):

    # obtain abp file
    testdata = pd.read_csv(file_name, header=None)
    #print testdata
    testdata_to_transpose = testdata.iloc[:,1]
    #print testdata_to_transpose
    testdata = np.transpose(testdata_to_transpose)
    testdata = testdata.reshape(1, -1)
    #print testdata

    # extract abp values
    #print testdata.shape
    leng = testdata.shape[1]-1
    #print leng
    #T = testdata.iloc[:,leng]
    T =  np.array(testdata[:,0:leng])
    #print T
    testdata = np.array(T)

    # once model is stored, then retrieve it
    model = joblib.load('svm-model-0.pkl') 

    # make predictions
    predicted = model.predict(testdata)

    return predicted

"predicted" variable returns [0.] which is not JSON serialisable. How do I rectify this?
```

**Comment by rliekarmp** [comment]
Thanks shouldsee! Your fix solved my save_html problem. I was getting "array is not JSON serializable html" when trying to save a scatter plot.

**Comment by bobleujr** [comment]
It seems to me that this issue hasn't been solved in the latest release? I've got the latest version and had to fix it manually too. Thanks anyway @shouldsee !

**Comment by aflaxman** [comment]
I'll merge a pull request if someone creates one.  Bonus points if the automatic tests all pass!

**Comment by TastyMuffins** [comment]
Suggested fix also resolved my issue.

**Comment by jason-neal** [comment]
Since javadba did not make a PR out of their commit I duplicated it.

**Comment by beukueb** [comment]
This is still an issue with
`matplotlib==2.2.2
mpld3==0.3`

I fix it manually by overwriting mpld3._display.NumpyEncoder in my program

`#mpld3 hack
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        import numpy as np
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)
from mpld3 import _display
_display.NumpyEncoder = NumpyEncoder
`

**Comment by addinall** [comment]
Is there a production fix for this as yet?  I introduced mpld3 into a Python project and am getting the same errors.  Cheers!

**Comment by jason-neal** [comment]
This fix should be resolved in master. There has not been a release of mpl3d in almost 2 years. i do not know when/if there will be another as it is not actively unmaintained...

**Comment by bryevdv** [comment]
@aflaxman @jakevdp perhaps it would be worth considering archiving this repository to indicate more clearly that the project is unmaintained:

https://help.github.com/articles/archiving-a-github-repository/

I did this for `bokeh/bkcharts`

**Comment by aflaxman** [comment]
@cliffckerr and company are planning to revive this project!  if that has changed, i think archiving is a great idea.

**Comment by shouldsee** [comment]
I have missed the days with mpld3+ Django. Not sure I will be of any help but please keep this alive!

Sent from my iPhone

On 14 Jul 2018, at 00:01, Abraham Flaxman <notifications@github.com<mailto:notifications@github.com>> wrote:


@cliffckerr<https://github.com/cliffckerr> and company are planning to revive this project! if that has changed, i think archiving is a great idea.

**Comment by addinall** [comment]
Thanks all.  I did not realise the code was unmaintained.  It sounded perfect for my needs.
Cheers, Mark.

**Comment by cliffckerr** [comment]
@addinall @aflaxman We are indeed reviving it! We are currently working on our fork (https://github.com/optimamodel/mpld3) but once everything is stable we'll be merging back here.

**Comment by aflaxman** [comment]
👍

**Comment by jjaimon** [comment]
Similar issue exists with fig_to_dict() as well.  The returned dict cannot be serialized to json due to included ndarray unless right encoder is passed.   One way to ovecome the issue is by using the internal NumpyEncoder class itself.  For eg. 
```
from mpld3._display import NumpyEncoder
json.dumps(mpld3.fig_to_dict(fig), cls=NumpyEncoder)
```

**Comment by carlosa2** [comment]
> This is still an issue with
> `matplotlib==2.2.2 mpld3==0.3`
> 
> I fix it manually by overwriting mpld3._display.NumpyEncoder in my program
> 
> ```
> #mpld3 hack
> class NumpyEncoder(json.JSONEncoder):
>     def default(self, obj):
>         import numpy as np
>         if isinstance(obj, np.ndarray):
>             return obj.tolist()
>         return json.JSONEncoder.default(self, obj)
> from mpld3 import _display
> _display.NumpyEncoder = NumpyEncoder
> ```



> This is still an issue with
> `matplotlib==2.2.2 mpld3==0.3`
> 
> I fix it manually by overwriting mpld3._display.NumpyEncoder in my program
> 
> ```
> #mpld3 hack
> class NumpyEncoder(json.JSONEncoder):
>     def default(self, obj):
>         import numpy as np
>         if isinstance(obj, np.ndarray):
>             return obj.tolist()
>         return json.JSONEncoder.default(self, obj)
> from mpld3 import _display
> _display.NumpyEncoder = NumpyEncoder
> ```

Thank you very much!
You´re a genius!
And I know that because I barely know anything of python and I was able to fix it myself.
